title: Investigate a Dataset
author: Ioannis K Breier
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Project 2 of the Udacity Data Analyst Nanodegree.
#baseurl: "/minima"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#markdown: kramdown
theme: jekyll-theme-dinky
exclude:
  - Gemfile
  - Gemfile.lock
