title: Exploratory Investigattion of the Titanic Dataset
author: Ioannis K Breier
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  _Based on Project 2 of the Udacity Data Analyst Nanodegree._
#baseurl: "/minima"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#markdown: kramdown
theme: jekyll-theme-dinky
exclude:
  - Gemfile
  - Gemfile.lock
